server:
  port: 2002

eureka:
  instance:
    hostname: eureka2002.com
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eureka2001.com:2001/eureka/,http://eureka2003.com:2003/eureka/ # 集群
