server:
  port: 2001

eureka:
  instance:
    hostname: eureka2001.com
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eureka2002.com:2002/eureka/,http://eureka2003.com:2003/eureka/ # 集群
