server:
  port: 4001
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:   #是否与服务注册于发现组件进行结合，通过 serviceId 转发到具体的服务实例
        locator:
          enabled: true
      routes:
        - id: test-proxy #payment_routh    #路由的ID，没有固定规则但要求唯一，简易配合服务名
          uri: lb://user     #匹配后提供服务的路由地址
          predicates:
            - Path=/user-service/**     #断言，路径相匹配的进行路由
          filters:
            - RewritePath=/user-service/(?<segment>.*), /$\{segment} #路径重写，通过正则表达式的方式，去掉路径中的user-service
#            - RewritePath=/user-service/**，/**
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka2001.com:2001/eureka/,http://eureka2002.com:2002/eureka/,http://eureka2003.com:2003/eureka/