server:
  port: 2003

eureka:
  instance:
    hostname: eureka2003.com
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eureka2001.com:2001/eureka/,http://eureka2002.com:2002/eureka/ # 集群
